//! Per-head world geometry — the spatial half of the HeadCtx fed to
//! apply_effects. Twin of `shared/geometry.ts`; the two must stay in lockstep
//! or the engines' spatial effects diverge.
//!
//! All values are QUANTIZED to 10⁻⁶ m at the build boundary. IEEE add/multiply
//! are bit-deterministic across the two engines, but sin/cos are not (V8 vs
//! libm can differ in the last ulp); quantizing here means that difference can
//! never reach the per-tick effect maths, so byte parity holds without pinning
//! trig implementations.

use std::collections::HashMap;

use crate::profiles::profile_of;
use crate::types::Project;

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct HeadGeom {
    /// world position, metres — x stage left→right, y up, z toward audience
    pub x: f64,
    pub y: f64,
    pub z: f64,
    /// the head's offset along the fixture's local X axis, metres
    pub along: f64,
    /// grid coordinates. Every profile today is a single row along local X, so
    /// row is 0 and col is the head index; B1 (GDTF geometry parsing) makes
    /// these honest for real pixel grids.
    pub row: usize,
    pub col: usize,
}

/// Geometry for a head the builder could not place (unknown profile — the
/// renderer's heads-map skip already excludes these from output). Matches the
/// repaired-default fixture position so a defensive fallback is never NaN.
pub const NO_GEOM: HeadGeom = HeadGeom { x: 0.0, y: 2.0, z: 0.0, along: 0.0, row: 0, col: 0 };

/// floor(v·1e6 + 0.5) — written identically in both languages because
/// Math.round and Rust's f64::round disagree on negative halves. Non-finite
/// input maps to 0: sanitize repairs upstream, this is the last resort.
fn q(v: f64) -> f64 {
    if v.is_finite() { (v * 1e6 + 0.5).floor() / 1e6 } else { 0.0 }
}

/// Build world geometry for every head of every fixture, keyed
/// (fixture id, head) — the same key the renderer's heads map uses, from the
/// same enumeration (fixtures × profile heads, builtin profile first), so
/// every rendered head has an entry by construction.
///
/// The formula is the repo's canonical placement, verbatim from the two 3D
/// previzes (three.js rotation.order 'YXZ' / bevy EulerRot::YXZ):
///
/// `world = pos + Ry(rotY) · Rx(rotX) · Rz(rotZ) · (offset, 0, 0)`
///
/// radians, right-handed Y-up; yaw maps local +X to (cosθ, 0, −sinθ) — the
/// convention core/src/mvr.rs documents and MVR import assumes. (The 2D plan
/// view historically used +sinθ; it is the outlier, not this.)
///
/// Rebuild is gen-gated by the caller — this walks every head, so it must run
/// on project changes only, never per tick.
pub fn build_geometry(p: &Project) -> HashMap<(String, usize), HeadGeom> {
    let mut out = HashMap::new();
    for f in &p.fixtures {
        // mirror Prof::resolve in renderer.rs: builtin first, then compiled
        let offsets: Vec<f64> = if let Some(bp) = profile_of(&f.profile_id) {
            bp.heads.iter().map(|h| h.offset).collect()
        } else if let Some(cp) = p.profiles.get(&f.profile_id) {
            cp.heads.iter().map(|h| h.offset).collect()
        } else {
            continue;
        };
        let yaw = f.rot_y;
        let pitch = f.rot_x.unwrap_or(0.0);
        let roll = f.rot_z.unwrap_or(0.0);
        let (cy, sy) = (yaw.cos(), yaw.sin());
        let (cx, sx) = (pitch.cos(), pitch.sin());
        let (cz, sz) = (roll.cos(), roll.sin());
        for (i, o) in offsets.into_iter().enumerate() {
            // Rz then Rx then Ry applied to (o, 0, 0), each step written out so
            // the operation ORDER is textually identical to the TS twin (IEEE
            // ops are deterministic given the same inputs in the same order).
            let ax = o * cz;
            let ay = o * sz;
            let by = ay * cx;
            let bz = ay * sx;
            let wx = ax * cy + bz * sy;
            let wz = -ax * sy + bz * cy;
            out.insert(
                (f.id.clone(), i),
                HeadGeom {
                    x: q(f.pos.x + wx),
                    y: q(f.pos.y + by),
                    z: q(f.pos.z + wz),
                    along: q(o),
                    row: 0,
                    col: i,
                },
            );
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The golden vectors are the cross-language contract: generated by an
    /// INDEPENDENT third implementation (Python) of the same formula and
    /// quantizer, and asserted EXACTLY here and in engine/test/smoke.ts. If
    /// either engine's trig lands a quantization boundary differently, this is
    /// where it surfaces — as an exact-value mismatch, not a byte drift later.
    #[test]
    fn golden_vectors_match_exactly() {
        let golden: serde_json::Value =
            serde_json::from_str(include_str!("../tests/data/geometry_golden.json"))
                .expect("golden file parses");
        let project: Project = serde_json::from_value(golden["project"].clone())
            .expect("golden project deserializes");
        let geom = build_geometry(&project);
        let expected = golden["expected"].as_object().expect("expected map");
        assert_eq!(geom.len(), expected.len(), "head count mismatch");
        for (key, want) in expected {
            let (fid, head) = key.rsplit_once(':').expect("key shape fid:head");
            let g = geom
                .get(&(fid.to_string(), head.parse().unwrap()))
                .unwrap_or_else(|| panic!("missing geometry for {key}"));
            // exact f64 equality — quantization is the tolerance
            assert_eq!(g.x, want["x"].as_f64().unwrap(), "{key} x");
            assert_eq!(g.y, want["y"].as_f64().unwrap(), "{key} y");
            assert_eq!(g.z, want["z"].as_f64().unwrap(), "{key} z");
            assert_eq!(g.along, want["along"].as_f64().unwrap(), "{key} along");
            assert_eq!(g.row, want["row"].as_u64().unwrap() as usize, "{key} row");
            assert_eq!(g.col, want["col"].as_u64().unwrap() as usize, "{key} col");
        }
    }

    #[test]
    fn unknown_profile_gets_no_entry() {
        let golden: serde_json::Value =
            serde_json::from_str(include_str!("../tests/data/geometry_golden.json")).unwrap();
        let project: Project = serde_json::from_value(golden["project"].clone()).unwrap();
        let geom = build_geometry(&project);
        assert!(
            !geom.keys().any(|(fid, _)| fid == "ghost"),
            "a fixture with an unknown profile must be skipped, like the heads map skips it"
        );
    }

    #[test]
    fn compiled_profile_offsets_are_consumed_not_rederived() {
        // A GDTF-imported strip: offsets are whatever the compile stored
        // (fabricated or parsed) — geometry must read them, never recompute
        // spacing from the head index. Mirrored in engine/test/smoke.ts with
        // the same literals.
        use crate::cprofile::{CHead, CompiledProfile};
        use crate::profiles::HeadKind;
        let heads: Vec<CHead> = [-0.5, -0.1667, 0.1667, 0.5]
            .iter()
            .map(|&o| CHead { kind: HeadKind::Rgb, offset: o, label: String::new() })
            .collect();
        let cp = CompiledProfile {
            id: "imported-strip".into(),
            manufacturer: "T".into(),
            model: "Strip".into(),
            mode: "4px".into(),
            footprint: 12,
            heads,
            channels: vec![],
            beam_deg: 20.0,
            virtual_dimmer: false,
            credit: None,
        };
        let mut project: Project =
            serde_json::from_str(r#"{"version":1,"universes":[],"fixtures":[{"id":"s","name":"S","profileId":"imported-strip","universeId":"u1","address":1,"pos":{"x":0,"y":3,"z":0},"rotY":0}],"groups":[],"layers":[],"columns":[]}"#)
                .unwrap();
        project.profiles.insert("imported-strip".into(), cp);
        let geom = build_geometry(&project);
        assert_eq!(geom.len(), 4);
        assert_eq!(geom[&("s".to_string(), 0)].x, -0.5);
        assert_eq!(geom[&("s".to_string(), 1)].x, -0.1667);
        assert_eq!(geom[&("s".to_string(), 3)].x, 0.5);
        assert_eq!(geom[&("s".to_string(), 2)].along, 0.1667);
    }

    #[test]
    fn quantizer_matches_the_ts_twin_on_negative_halves() {
        // Math.round and f64::round disagree at -0.5 — both twins use
        // floor(v·1e6 + 0.5) instead. -0.0000005 · 1e6 = -0.5 → floor(0.0) = 0.
        assert_eq!(q(-0.0000005), 0.0, "negative half rounds up (toward +inf), as Math.round does");
        assert_eq!(q(0.0000005), 0.000001);
        assert_eq!(q(f64::NAN), 0.0, "non-finite is absorbed, never propagated");
        assert_eq!(q(f64::INFINITY), 0.0);
        assert_eq!(q(1.23456789), 1.234568);
    }
}
