//! The local fixture library: `~/Library/Application Support/LIGHT/fixtures`.
//!
//! What is in it: `.gdtf` files — downloaded from GDTF Share (share.rs writes
//! them there), imported from a file (the Rig view saves a copy), and the
//! generic layouts LIGHT ships (shared/fixtures, seeded once per SEED_VERSION,
//! never overwriting a file that exists). The engine never reads this
//! directory: a project carries compiled profiles, so a show opened on a
//! machine that has never seen the fixture still works — the library is where
//! a fixture comes FROM when it is patched.
//!
//! Content rights (docs/feature-backlog.md, decision 1): only LIGHT's own
//! generics ship. Share files are the operator's downloads, per its terms, and
//! stay on this machine.

use light_core::gdtf::parse_gdtf;
use light_core::profiles::HeadKind;
use serde::Serialize;
use std::path::{Path, PathBuf};

// SEEDS: &[(file name, description.xml)] — generated by build.rs from
// shared/fixtures/*.gdtf.xml, so a new generic is a new file there and nothing
// else.
include!(concat!(env!("OUT_DIR"), "/seeds.rs"));

/// Bump when a generic is added or corrected: seeding runs again and writes
/// only the files that are missing.
pub const SEED_VERSION: &str = "1";

fn dir() -> PathBuf {
    light_core::persist::fixture_dir()
}

/// A `.gdtf` is a zip holding `description.xml` — the shape `parse_gdtf` reads.
pub fn gdtf_bytes(description_xml: &str) -> Result<Vec<u8>, String> {
    use std::io::Write;
    let mut cursor = std::io::Cursor::new(Vec::new());
    {
        let mut z = zip::ZipWriter::new(&mut cursor);
        let opts = zip::write::SimpleFileOptions::default()
            .compression_method(zip::CompressionMethod::Deflated);
        z.start_file("description.xml", opts).map_err(|e| e.to_string())?;
        z.write_all(description_xml.as_bytes()).map_err(|e| e.to_string())?;
        z.finish().map_err(|e| e.to_string())?;
    }
    Ok(cursor.into_inner())
}

/// Seed the generics: once per SEED_VERSION, writing only what is missing.
/// Returns how many files were written.
pub fn seed(dir: &Path) -> Result<usize, String> {
    let marker = dir.join(".seed-version");
    if std::fs::read_to_string(&marker).map(|s| s.trim() == SEED_VERSION).unwrap_or(false) {
        return Ok(0);
    }
    std::fs::create_dir_all(dir).map_err(|e| format!("cannot create {dir:?}: {e}"))?;
    let mut written = 0;
    for (name, xml) in SEEDS {
        let path = dir.join(name);
        if path.exists() {
            continue; // the operator's copy, whatever they did to it
        }
        std::fs::write(&path, gdtf_bytes(xml)?).map_err(|e| format!("cannot write {name}: {e}"))?;
        written += 1;
    }
    std::fs::write(&marker, SEED_VERSION).map_err(|e| e.to_string())?;
    Ok(written)
}

/// Seed the app's own library; logged, never fatal.
pub fn seed_default() -> Result<usize, String> {
    seed(&dir())
}

/// One DMX mode of a library file, as the compiler makes it.
#[derive(Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct LibraryMode {
    pub name: String,
    pub footprint: usize,
    /// the profile id `importGdtf` will give it — the same compiler, so the
    /// same id, which is how the picker knows whether the project has it
    pub profile_id: String,
    pub heads: usize,
    pub kind: String,
    pub virtual_dimmer: bool,
}

#[derive(Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct LibraryEntry {
    pub file: String,
    pub manufacturer: String,
    pub model: String,
    pub modes: Vec<LibraryMode>,
    /// one of the generics LIGHT ships
    pub seeded: bool,
    /// a file the compiler could not read — listed, not hidden
    pub error: Option<String>,
}

/// Everything in the directory, parsed: the operator's own files first, the
/// generics after, both by manufacturer and model.
pub fn scan(dir: &Path) -> Vec<LibraryEntry> {
    let Ok(rd) = std::fs::read_dir(dir) else { return Vec::new() };
    let mut out = Vec::new();
    for e in rd.flatten() {
        let name = e.file_name().to_string_lossy().into_owned();
        if !name.to_lowercase().ends_with(".gdtf") {
            continue;
        }
        let seeded = SEEDS.iter().any(|(n, _)| *n == name);
        let parsed = std::fs::read(e.path())
            .map_err(|err| err.to_string())
            .and_then(|bytes| parse_gdtf(&bytes));
        match parsed {
            Ok(profiles) if !profiles.is_empty() => out.push(LibraryEntry {
                file: name,
                manufacturer: profiles[0].manufacturer.clone(),
                model: profiles[0].model.clone(),
                modes: profiles
                    .iter()
                    .map(|p| LibraryMode {
                        name: p.mode.clone(),
                        footprint: p.footprint,
                        profile_id: p.id.clone(),
                        heads: p.heads.len(),
                        kind: format!("{:?}", p.heads.first().map(|h| h.kind).unwrap_or(HeadKind::Dimmer)).to_lowercase(),
                        virtual_dimmer: p.virtual_dimmer,
                    })
                    .collect(),
                seeded,
                error: None,
            }),
            Ok(_) => out.push(unreadable(name, seeded, "no usable DMX modes".into())),
            Err(err) => out.push(unreadable(name, seeded, err)),
        }
    }
    out.sort_by(|a, b| {
        a.seeded
            .cmp(&b.seeded)
            .then(a.manufacturer.to_lowercase().cmp(&b.manufacturer.to_lowercase()))
            .then(a.model.to_lowercase().cmp(&b.model.to_lowercase()))
    });
    out
}

fn unreadable(file: String, seeded: bool, error: String) -> LibraryEntry {
    LibraryEntry { model: file.clone(), file, manufacturer: String::new(), modes: Vec::new(), seeded, error: Some(error) }
}

/// A library file name from whatever arrived: no path, no parent, `.gdtf`.
fn safe_name(name: &str) -> Result<String, String> {
    let base = name.rsplit(['/', '\\']).next().unwrap_or("").trim();
    if base.is_empty() || base.contains("..") {
        return Err(format!("not a fixture file name: {name}"));
    }
    let mut safe: String = base
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.' | ' ') { c } else { '_' })
        .collect();
    if !safe.to_lowercase().ends_with(".gdtf") {
        safe.push_str(".gdtf");
    }
    Ok(safe)
}

/// Everything in the library, with what the compiler makes of each file.
#[tauri::command]
pub async fn library_info() -> Vec<LibraryEntry> {
    scan(&dir())
}

/// Keep a fixture file the operator imported, so the next show starts with
/// it. Compiled first — a file the compiler cannot read is not worth keeping —
/// and written under a safe name, which is returned.
#[tauri::command]
pub async fn library_save(name: String, data: String) -> Result<String, String> {
    let bytes = light_core::state::base64_decode(&data)?;
    parse_gdtf(&bytes)?;
    let safe = safe_name(&name)?;
    let d = dir();
    std::fs::create_dir_all(&d).map_err(|e| format!("cannot create {d:?}: {e}"))?;
    std::fs::write(d.join(&safe), &bytes).map_err(|e| format!("cannot write {safe}: {e}"))?;
    Ok(safe)
}

/// Remove one file. Fixtures already patched keep their compiled profile —
/// the project carries it — so this only changes what the picker offers.
#[tauri::command]
pub async fn library_remove(name: String) -> Result<(), String> {
    if name.is_empty() || name.contains('/') || name.contains('\\') || name.contains("..") || !name.to_lowercase().ends_with(".gdtf") {
        return Err(format!("not a library fixture: {name}"));
    }
    std::fs::remove_file(dir().join(&name)).map_err(|e| format!("cannot remove {name}: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// (file, [(mode, footprint, heads, virtual dimmer)]) — the layout each
    /// generic promises in its name, as the compiler actually reads it.
    const EXPECT: &[(&str, &[(&str, usize, usize, bool)])] = &[
        ("generic-dimmer-strobe.gdtf", &[("2ch D-S", 2, 1, false)]),
        ("generic-rgb-dimmer.gdtf", &[("4ch D-RGB", 4, 1, false), ("4ch RGB-D", 4, 1, false)]),
        ("generic-rgb-dimmer-strobe.gdtf", &[("5ch D-RGB-S", 5, 1, false), ("5ch RGB-D-S", 5, 1, false), ("5ch RGB-S-D", 5, 1, false)]),
        ("generic-rgbw-dimmer.gdtf", &[("5ch D-RGBW", 5, 1, false), ("5ch RGBW-D", 5, 1, false)]),
        ("generic-rgbw-dimmer-strobe.gdtf", &[("6ch D-RGBW-S", 6, 1, false), ("6ch RGBW-D-S", 6, 1, false)]),
        ("generic-rgba.gdtf", &[("4ch RGBA", 4, 1, true), ("5ch D-RGBA", 5, 1, false), ("6ch D-RGBA-S", 6, 1, false)]),
        ("generic-rgbaw.gdtf", &[("5ch RGBAW", 5, 1, true), ("6ch D-RGBAW", 6, 1, false), ("7ch D-RGBAW-S", 7, 1, false)]),
        ("generic-rgbawuv.gdtf", &[("6ch RGBAWUV", 6, 1, true), ("7ch D-RGBAWUV", 7, 1, false), ("8ch D-RGBAWUV-S", 8, 1, false)]),
        ("generic-bar-4-rgb.gdtf", &[("12ch 4xRGB", 12, 4, true)]),
        ("generic-bar-8-rgb.gdtf", &[("24ch 8xRGB", 24, 8, true)]),
        ("generic-bar-4-rgbw.gdtf", &[("16ch 4xRGBW", 16, 4, true)]),
        ("generic-strip-16-rgb.gdtf", &[("48ch 16xRGB", 48, 16, true)]),
    ];

    #[test]
    fn every_generic_compiles_to_the_layout_its_name_promises() {
        assert_eq!(EXPECT.len(), SEEDS.len(), "every seed file has a row here");
        for (file, modes) in EXPECT {
            let xml = SEEDS.iter().find(|(n, _)| n == file).unwrap_or_else(|| panic!("{file} is not seeded")).1;
            let profiles = parse_gdtf(&gdtf_bytes(xml).unwrap()).unwrap_or_else(|e| panic!("{file}: {e}"));
            assert_eq!(profiles.len(), modes.len(), "{file}: mode count");
            for (p, (mode, footprint, heads, virtual_dimmer)) in profiles.iter().zip(modes.iter()) {
                assert_eq!(p.manufacturer, "Generic", "{file}");
                assert_eq!(p.mode, *mode, "{file}");
                assert_eq!(p.footprint, *footprint, "{file} {mode}: footprint");
                assert_eq!(p.heads.len(), *heads, "{file} {mode}: heads");
                assert_eq!(p.virtual_dimmer, *virtual_dimmer, "{file} {mode}: virtual dimmer");
                let kind = p.heads[0].kind;
                assert_eq!(kind == HeadKind::Rgb, mode.contains("RGB"), "{file} {mode}: head kind {kind:?}");
                // a strobe mode really strobes: some channel case reads the strobe source
                let strobes = p.channels.iter().any(|c| format!("{:?}", c.cases).contains("Strobe"));
                assert_eq!(strobes, mode.ends_with("-S") || mode.contains("-S-"), "{file} {mode}: strobe wiring");
            }
        }
    }

    fn scratch(tag: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!("light-library-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&d);
        d
    }

    #[test]
    fn seeding_is_once_per_version_and_never_overwrites() {
        let d = scratch("seed");
        assert_eq!(seed(&d).unwrap(), SEEDS.len(), "a fresh directory gets every generic");
        assert_eq!(seed(&d).unwrap(), 0, "the marker stops a second pass");
        // the operator edited one and deleted another
        let (edited, _) = SEEDS[0];
        let (deleted, _) = SEEDS[1];
        std::fs::write(d.join(edited), b"theirs").unwrap();
        std::fs::remove_file(d.join(deleted)).unwrap();
        std::fs::remove_file(d.join(".seed-version")).unwrap(); // a version bump, in effect
        assert_eq!(seed(&d).unwrap(), 1, "only the missing file comes back");
        assert_eq!(std::fs::read(d.join(edited)).unwrap(), b"theirs", "an existing file is never overwritten");
        let listed = scan(&d);
        assert_eq!(listed.len(), SEEDS.len());
        assert!(listed.iter().all(|e| e.seeded));
        let broken = listed.iter().find(|e| e.file == edited).unwrap();
        assert!(broken.error.is_some(), "the edited file no longer parses and says so");
        assert!(listed.iter().filter(|e| e.error.is_none()).all(|e| !e.modes.is_empty()));
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn a_bad_file_is_listed_with_its_error_and_the_rest_sorted() {
        let d = scratch("scan");
        std::fs::create_dir_all(&d).unwrap();
        std::fs::write(d.join("junk.gdtf"), b"not a zip").unwrap();
        std::fs::write(d.join("zzz-acme.gdtf"), gdtf_bytes(SEEDS[0].1.replace("Generic", "Acme").as_str()).unwrap()).unwrap();
        std::fs::write(d.join(SEEDS[0].0), gdtf_bytes(SEEDS[0].1).unwrap()).unwrap();
        let listed = scan(&d);
        assert_eq!(listed.len(), 3);
        assert_eq!(listed[0].manufacturer, "", "the unreadable file sorts first, with no manufacturer");
        assert!(listed[0].error.is_some());
        assert_eq!(listed[1].manufacturer, "Acme", "the operator's own file before the generics");
        assert!(!listed[1].seeded);
        assert!(listed[2].seeded);
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn names_are_kept_inside_the_library() {
        assert_eq!(safe_name("Robe Spiider.gdtf").unwrap(), "Robe Spiider.gdtf");
        assert_eq!(safe_name("/tmp/x/thing").unwrap(), "thing.gdtf", "a path becomes its last segment");
        assert_eq!(safe_name("a:b*c.gdtf").unwrap(), "a_b_c.gdtf");
        // a path is reduced to its last segment, so it cannot leave the directory
        assert_eq!(safe_name("../../etc/passwd").unwrap(), "passwd.gdtf");
        assert!(safe_name("..").is_err());
        assert!(safe_name("").is_err());
        assert!(safe_name("/").is_err());
    }
}
